spring:
  application:
    name: register-users-employees
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        jdbc:
          time_zone: America/Sao_Paulo
server:
  port: ${PORT:8083}
